<?php
// $Id$

/**
 * @file
 *
 *
 *
 *
 */

/**
 * Implements hook_help().
 */
function starter_help($path, $arg) {
  if ($path == 'admin/help#starter') {
    return t('A demo module.');
  }
}

/**
 * Implements hook_menu().
 */
function starter_menu() {
  $items['main'] = array(
    'title' => 'Main page',
    'page callback' => 'main_page',
    'access callback' => TRUE,
  );

  $items['not_found'] = array(
    'title' => '404 Page not found',
    'page callback' => 'not_found',
    'access callback' => TRUE,
  );

  $items['no_access'] = array(
    'title' => '403 Access denied',
    'page callback' => 'no_access',
    'access callback' => TRUE,
  );

    return $items;
}

/**
 * Page callback for /menu.
 */
function main_page() {
  return 'This is the main page';
}

/**
 * Page callback for /not_found.
 */
function not_found() {
  return 'Requested page not found. Its a shame...';
}

/**
 * Page callback for /no_access.
 */
function no_access() {
  return 'Access denied. Fuck you.';
}

/**
 * Implements hook_block_info().
 */
function starter_block_info() {
  $blocks = array();

  $blocks['list_modules'] = array(
    'info' => t('A listing of all of the enabled modules'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function starter_block_view($block_name = '') {
  $block = array();

  if ($block_name == 'list_modules') {
    if (user_access('view block')) {

        $list = module_list();

        $theme_args = array('items' => $list, 'type' => 'ol');
        $content = theme('item_list', $theme_args);

        $block = array(
          'subject' => t('Enabled Modules'),
          'content' => $content,
        );
    }
    else {
      $block = array(
        'subject' => t('Enabled Modules'),
        'content' => 'You don\'t have enough permission',
      );
    }
  }

  return $block;
}

/**
 * Implements hook_permission().
 */
function starter_permission() {
  return array(
    'view block' => array(
      'title' => t('Modules list'),
      'description' => t('View list of modules in block.'),
    ),
  );
}

?>
